# Generated by Django 4.2.7 on 2023-11-27 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_created=True, verbose_name='Date Created')),
                ('firstName', models.CharField(max_length=25, null=True, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=25, null=True, verbose_name='Last Name')),
                ('mobile', models.CharField(max_length=25, null=True, verbose_name='Mobile Number')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email Address')),
                ('dateOfBirth', models.DateField(null=True, verbose_name='Date of Birth')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
