# Generated by Django 4.2.7 on 2023-12-02 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_created=True, verbose_name='Date Created')),
                ('date', models.DateField(null=True, verbose_name='Date')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.player')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=25, null=True, verbose_name='Day of the week')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.IntegerField(null=True, verbose_name='Start Time')),
                ('choice', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=3, verbose_name='Choice')),
                ('endTime', models.IntegerField(null=True, verbose_name='End Time')),
                ('days', models.ManyToManyField(blank=True, to='app.day')),
            ],
        ),
        migrations.CreateModel(
            name='Turf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_created=True, verbose_name='Date Created')),
                ('ownerName', models.CharField(max_length=25, null=True, verbose_name='First Name')),
                ('turfName', models.CharField(max_length=25, null=True, verbose_name='Turf Name')),
                ('location', models.CharField(max_length=200, null=True, verbose_name='Location ')),
                ('phoneNumber', models.CharField(max_length=25, null=True, verbose_name='Phone Number')),
                ('pricePerSlot', models.FloatField(max_length=3, null=True, verbose_name='Price Per Slot')),
                ('fieldSize', models.CharField(choices=[('5s', '5s'), ('7s', '7s')], max_length=3, verbose_name='fieldSize')),
                ('slots', models.ManyToManyField(blank=True, to='app.timeslot')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField(auto_created=True, verbose_name='Date Created')),
                ('mode', models.CharField(choices=[('UPI', 'UPI'), ('Cash', 'Cash')], max_length=25, verbose_name='Payment Mode')),
                ('screenshot', models.ImageField(null=True, upload_to='', verbose_name='Payment Screenshot Upload')),
                ('amount', models.FloatField(max_length=10, null=True, verbose_name='Toatl Amount ')),
                ('booking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.booking')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.player')),
                ('turf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.turf')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='timeSlot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.timeslot'),
        ),
        migrations.AddField(
            model_name='booking',
            name='turf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.turf'),
        ),
    ]
