# Generated by Django 4.2.7 on 2023-12-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_booking_day_timeslot_turf_payment_booking_timeslot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='choice',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='endAMPM',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', max_length=3, verbose_name='AM / PM'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='startAMPM',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', max_length=3, verbose_name='AM / PM'),
        ),
        migrations.AlterField(
            model_name='turf',
            name='ownerName',
            field=models.CharField(max_length=25, null=True, verbose_name='Owner Name'),
        ),
    ]
