# Generated by Django 4.2.7 on 2023-12-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_payment_amount_alter_payment_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
    ]
