# Generated by Django 4.2.7 on 2023-12-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_player_datecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='turf',
            name='fieldSize',
            field=models.CharField(choices=[('5s', '5s'), ('7s', '7s')], default='5s', max_length=3, verbose_name='fieldSize'),
        ),
    ]
