# Generated by Django 4.2.7 on 2023-12-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_turf_datecreated_alter_turf_fieldsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='dateCreated',
            field=models.DateTimeField(auto_created=True, null=True, verbose_name='Date Created'),
        ),
    ]
