# Generated by Django 4.2.7 on 2023-12-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_booking_datecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='dateCreated',
            field=models.DateTimeField(auto_created=True, null=True, verbose_name='Date Created'),
        ),
    ]
