# Generated by Django 4.2.7 on 2023-12-18 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_timeslot_days_delete_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turf',
            name='ownerName',
        ),
    ]
